### ISSUE TITLE
Semgrep version 0.1.5 is not compatible with the current version of the IDE

### ISSUE THREAD

**Issue by aramhovsepyan** [semgrep/semgrep-intellij#31]
Since the latest IntelliJ IDE update to version PS-233.11799.232 the Semgrep plugin doesn't even start. I get an error message that the plugin is only compatible with versions below 232. 
Is there any support for this plugin as I have reported an issue a couple of weeks back without any response.
Thanks.

**Comment by ajbt200128** [comment]
hey, sorry we missed the earlier issue! We'll look into that one and this one!

**Comment by aramhovsepyan** [comment]
Hi,
Any update on this one. Still doesn't work. Semgrep is one of the best SAST out there and I am a big fan of it. Yet having an IDE plugin to indicate issues is absolutely critical for a mature appsec program.
Thanks.

**Comment by ajbt200128** [comment]
Hi @aramhovsepyan. The error message about compatibility should be fixed. What error are you getting now? Can you follow the steps in this comment to provide logs? https://github.com/semgrep/semgrep-intellij/issues/52#issuecomment-2037649861

**Comment by aramhovsepyan** [comment]
Hi Austin,
This is what I can find in the startup log. When I click on Scan with Semgrep or anything else nothing happens (no logs).
I hope this is what you were looking for.
PS: I have libev installed.

`2024-04-19 14:08:34,148 [  22958]   INFO - #c.i.p.l.i.LspServerImpl - SemgrepLspServerDescriptor@sammy(Initializing;0): Starting LSP server
2024-04-19 14:08:34,150 [  22960]   INFO - #c.i.p.l.a.LspServerDescriptor - SemgrepLspServerDescriptor@sammy: starting LSP server: /opt/homebrew/bin/semgrep [lsp]
2024-04-19 14:08:34,226 [  23036]   INFO - #c.i.p.l.i.LspServerImpl - SemgrepLspServerDescriptor@sammy(Initializing;0): LSP server process started: /opt/homebrew/bin/semgrep lsp
2024-04-19 14:08:34,710 [  23520]   INFO - #c.i.p.l.i.LspServerImpl - SemgrepLspServerDescriptor@sammy(Initializing;0): STDERR: [31mError: exception Lwt_sys.Not_available("libev_init")
2024-04-19 14:08:34,711 [  23521]   INFO - #c.i.p.l.i.LspServerImpl - SemgrepLspServerDescriptor@sammy(Initializing;0): STDERR: Raised by primitive operation at Lwt_engine.libev in file "src/unix/lwt_engine.ml", line 177, characters 13-28
2024-04-19 14:08:34,711 [  23521]   INFO - #c.i.p.l.i.LspServerImpl - SemgrepLspServerDescriptor@sammy(Initializing;0): STDERR: Called from Lwt_platform.set_engine in file "libs/lwt_platform/unix/Lwt_platform.ml", line 26, characters 35-60
2024-04-19 14:08:34,711 [  23521]   INFO - #c.i.p.l.i.LspServerImpl - SemgrepLspServerDescriptor@sammy(Initializing;0): STDERR: Called from LS.start in file "src/osemgrep/language_server/LS.ml", line 70, characters 2-28
2024-04-19 14:08:34,711 [  23521]   INFO - #c.i.p.l.i.LspServerImpl - SemgrepLspServerDescriptor@sammy(Initializing;0): STDERR: Called from Lsp_subcommand.run in file "src/osemgrep/cli_lsp/Lsp_subcommand.ml", line 50, characters 19-32
2024-04-19 14:08:34,711 [  23521]   INFO - #c.i.p.l.i.LspServerImpl - SemgrepLspServerDescriptor@sammy(Initializing;0): STDERR: Called from CLI.dispatch_subcommand in file "src/osemgrep/cli/CLI.ml", line 194, characters 19-50
2024-04-19 14:08:34,711 [  23521]   INFO - #c.i.p.l.i.LspServerImpl - SemgrepLspServerDescriptor@sammy(Initializing;0): STDERR: Called from CLI.safe_run in file "src/osemgrep/cli/CLI.ml", line 227, characters 8-12
2024-04-19 14:08:34,711 [  23521]   INFO - #c.i.p.l.i.LspServerImpl - SemgrepLspServerDescriptor@sammy(Initializing;0): STDERR: 
2024-04-19 14:08:34,711 [  23521]   INFO - #c.i.p.l.i.LspServerImpl - SemgrepLspServerDescriptor@sammy(Initializing;0): STDERR: Error: fatal error
2024-04-19 14:08:34,711 [  23521]   INFO - #c.i.p.l.i.LspServerImpl - SemgrepLspServerDescriptor@sammy(Initializing;0): STDERR: Exiting with error status 2: osemgrep lsp
2024-04-19 14:08:34,711 [  23521]   INFO - #c.i.p.l.i.LspServerImpl - SemgrepLspServerDescriptor@sammy(Initializing;0): STDERR: [0m
2024-04-19 14:08:34,712 [  23522]   INFO - #c.i.p.l.i.LspServerImpl - SemgrepLspServerDescriptor@sammy(Initializing;0): LSP server process terminated, exit code = 2, command line: /opt/homebrew/bin/semgrep lsp
2024-04-19 14:08:34,712 [  23522]   INFO - #c.i.p.l.i.LspServerImpl - SemgrepLspServerDescriptor@sammy(Initializing;0): Stopping LSP server unexpectedly
2024-04-19 14:08:43,410 [  32220]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.SdkEntity to files
2024-04-19 14:08:43,411 [  32221]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.LibraryEntity to files
2024-04-19 14:08:43,515 [  32325]   INFO - #c.i.a.o.PathMacrosImpl - Saved path macros: {}
2024-04-19 14:08:43,540 [  32350]   INFO - #c.i.c.ComponentStoreImpl - Saving appStringManipulationState took 11 ms
2024-04-19 14:08:45,927 [  34737]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.SdkEntity to files
2024-04-19 14:08:45,927 [  34737]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.LibraryEntity to files
2024-04-19 14:09:00,684 [  49494]   INFO - #c.i.o.p.DumbServiceImpl - enter dumb mode [compudoc]
2024-04-19 14:09:00,702 [  49512]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Running task: (dumb mode task) com.intellij.openapi.roots.impl.PushedFilePropertiesUpdaterImpl$MyDumbModeTask@6ee02a31 (reason: Push on VFS changes)
2024-04-19 14:09:00,707 [  49517]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Task finished: (dumb mode task) com.intellij.openapi.roots.impl.PushedFilePropertiesUpdaterImpl$MyDumbModeTask@6ee02a31 (reason: Push on VFS changes)
2024-04-19 14:09:00,727 [  49537]   INFO - #c.i.o.p.DumbServiceImpl - exit dumb mode [compudoc]
2024-04-19 14:09:11,196 [  60006]   INFO - #c.i.u.i.ProjectChangedFilesScanner - Retrieving changed during indexing files of sammy : 969 to update, calculated in 0ms
2024-04-19 14:09:14,659 [  63469]   INFO - #c.i.u.g.s.GistStorageImpl - Cleaning old huge-gists dirs from [/Users/aram/Library/Caches/JetBrains/PhpStorm2024.1/caches/huge-gists] ...
2024-04-19 14:09:14,660 [  63470]   INFO - #c.i.u.g.s.GistStorageImpl - Cleaning old huge-gists dirs finished
2024-04-19 14:09:16,929 [  65739]   INFO - #c.i.u.i.UnindexedFilesIndexer - Finished for sammy. Unindexed files update took 48794ms; general responsiveness: 1/48 sluggish; EDT responsiveness: 1/48 sluggish
2024-04-19 14:09:16,930 [  65740]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Task finished: (dumb mode task) UnindexedFilesIndexer[sammy, 6 iterators, reason: On project open]
2024-04-19 14:09:16,930 [  65740]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Running task: (dumb mode task) com.intellij.openapi.roots.impl.PushedFilePropertiesUpdaterImpl$MyDumbModeTask@554fb355 (reason: Push on VFS changes)
2024-04-19 14:09:16,973 [  65783]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Task finished: (dumb mode task) com.intellij.openapi.roots.impl.PushedFilePropertiesUpdaterImpl$MyDumbModeTask@554fb355 (reason: Push on VFS changes)
2024-04-19 14:09:16,973 [  65783]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Running task: (dumb mode task) UnindexedFilesIndexer[sammy, 0 iterators, reason: On refresh of files in sammy]
2024-04-19 14:09:16,974 [  65784]   INFO - #c.i.u.i.c.IndexUpdateRunner - Using 5 indexing and 4 writing threads for indexing
2024-04-19 14:09:17,023 [  65833]   INFO - #c.i.u.i.ProjectChangedFilesScanner - Retrieving changed during indexing files of sammy : 911 to update, calculated in 49ms
2024-04-19 14:09:22,277 [  71087]   INFO - #c.i.u.i.UnindexedFilesIndexer - Finished for sammy. Unindexed files update took 5303ms; general responsiveness: ok; EDT responsiveness: ok
2024-04-19 14:09:22,278 [  71088]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Task finished: (dumb mode task) UnindexedFilesIndexer[sammy, 0 iterators, reason: On refresh of files in sammy]
2024-04-19 14:09:22,278 [  71088]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Running task: (dumb mode task) UnindexedFilesIndexer[sammy, 0 iterators, reason: On refresh of files in sammy]
2024-04-19 14:09:22,279 [  71089]   INFO - #c.i.u.i.c.IndexUpdateRunner - Using 5 indexing and 4 writing threads for indexing
2024-04-19 14:09:22,279 [  71089]   INFO - #c.i.u.i.ProjectChangedFilesScanner - Retrieving changed during indexing files of sammy : 0 to update, calculated in 0ms
2024-04-19 14:09:22,304 [  71114]   INFO - #c.i.u.i.UnindexedFilesIndexer - Finished for sammy. Unindexed files update took 25ms; general responsiveness: ok; EDT responsiveness: ok
2024-04-19 14:09:22,304 [  71114]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Task finished: (dumb mode task) UnindexedFilesIndexer[sammy, 0 iterators, reason: On refresh of files in sammy]
2024-04-19 14:09:22,305 [  71115]   INFO - #c.i.o.p.DumbServiceImpl - exit dumb mode [sammy]
2024-04-19 14:09:22,306 [  71116]   INFO - Symfony-Plugin - Symfony Support: Project grace period started: sammy
2024-04-19 14:09:22,309 [  71119]   INFO - #c.j.p.c.ComposerSettingSyncConfigClient - Composer synchronization is enabled -> update IDE settings based on composer.json
2024-04-19 14:09:22,309 [  71119]   INFO - #c.j.p.c.ComposerSettingSyncConfigClient - Composer synchronization is enabled -> update IDE settings based on composer.json
2024-04-19 14:09:22,310 [  71120]   INFO - #c.j.p.c.ComposerSettingSyncConfigClient - Composer synchronization is enabled -> update IDE settings based on composer.json
2024-04-19 14:09:22,328 [  71138]   INFO - #c.j.p.c.ComposerSettingSyncConfigClient - Composer synchronization is enabled -> update IDE settings based on composer.json
2024-04-19 14:09:22,343 [  71153]   INFO - #c.i.p.m.i.ProjectDependenciesModelImpl - Count of declared packages: 87, imported packages: 87
2024-04-19 14:09:22,427 [  71237]   INFO - #c.i.v.l.d.i.VcsLogPersistentIndex - Indexing 21 commits in sammy
2024-04-19 14:09:22,552 [  71362]   INFO - #c.i.v.l.d.i.VcsLogPersistentIndex - 122ms for indexing 21 new commits out of 21 in sammy
2024-04-19 14:09:22,706 [  71516]   INFO - #c.i.v.l.d.i.IndexDiagnosticRunner - Index diagnostic for 33 commits in [file:///Users/aram/Documents/workspace/sammy] is completed
2024-04-19 14:10:14,257 [ 123067]   WARN - #c.i.p.l.i.LspServerImpl - SemgrepLspServerDescriptor@sammy(ShutdownUnexpectedly;0): Failed to start LSP server`

**Comment by ajbt200128** [comment]
What version of semgrep are you on? We had an issue with homebrew not properly building semgrep with LibEV awhile back, but that was fixed, so maybe it's come up again. As a temporary fix installing semgrep via pip should work

**Comment by aramhovsepyan** [comment]
Hi Austin,
Thanks, that seems to solve the immediate problem. However in the ide log files I still have a bunch of issues and semgrep scan doesn't produce any output. PS: semgrep scan in the command line works just fine.
Here is the log trace.
````pattern-either`, `patterns`, `pattern-regex` to be present
2024-04-24 07:33:36,601 [  18041]   INFO - #c.i.p.l.i.LspServerImpl - SemgrepLspServerDescriptor@sammy(Running;2): STDERR: [0m[14.58][WARNING]: skipping rule ssc-parity-b6b549011aae6c375f6ba63bcd743fdfbb98cf2d, error = Expected one of `pattern`, `pattern-either`, `patterns`, `pattern-regex` to be present
2024-04-24 07:33:36,601 [  18041]   INFO - #c.i.p.l.i.LspServerImpl - SemgrepLspServerDescriptor@sammy(Running;2): STDERR: [0m[14.58][WARNING]: skipping rule ssc-parity-c0c743c3c10a7e97d18a0167091b7a09b32bdd8a, error = Expected one of `pattern`, `pattern-either`, `patterns`, `pattern-regex` to be present
2024-04-24 07:33:36,601 [  18041]   INFO - #c.i.p.l.i.LspServerImpl - SemgrepLspServerDescriptor@sammy(Running;2): STDERR: [0m[14.58][WARNING]: skipping rule ssc-parity-d3cda6ffc12c5ca37b30e0bf58f748ca95bca032, error = Expected one of `pattern`, `pattern-either`, `patterns`, `pattern-regex` to be present
2024-04-24 07:33:36,601 [  18041]   INFO - #c.i.p.l.i.LspServerImpl - SemgrepLspServerDescriptor@sammy(Running;2): STDERR: [0m[14.58][WARNING]: skipping rule ssc-parity-e9f8aae7809b7dd8a5d99d9932c9da32cf6c3a3a, error = Expected one of `pattern`, `pattern-either`, `patterns`, `pattern-regex` to be present
2024-04-24 07:33:36,601 [  18041]   INFO - #c.i.p.l.i.LspServerImpl - SemgrepLspServerDescriptor@sammy(Running;2): STDERR: [0m[14.58][WARNING]: skipping rule ssc-parity-5a45542c10336b00b7960e3b062fcd81a107aea0, error = Expected one of `pattern`, `pattern-either`, `patterns`, `pattern-regex` to be present
2024-04-24 07:33:36,601 [  18041]   INFO - #c.i.p.l.i.LspServerImpl - SemgrepLspServerDescriptor@sammy(Running;2): STDERR: [0m[14.58][WARNING]: Got 0 errors while refreshing rules in language server
2024-04-24 07:33:36,647 [  18087]   INFO - #c.i.p.l.i.LspServerImpl - SemgrepLspServerDescriptor@sammy(Running;2): STDERR: [0m[14.63][WARNING]: Unhandled notification { "params": { "id": "3" }, "method": "$/cancelRequest", "jsonrpc": "2.0" }
2024-04-24 07:33:36,648 [  18088]   INFO - #c.i.p.l.i.LspServerImpl - SemgrepLspServerDescriptor@sammy(Running;2): STDERR: [0m[14.63][WARNING]: Unhandled notification { "params": { "id": "4" }, "method": "$/cancelRequest", "jsonrpc": "2.0" }
2024-04-24 07:33:36,648 [  18088]   INFO - #c.i.p.l.i.LspServerImpl - SemgrepLspServerDescriptor@sammy(Running;2): STDERR: [0m[14.63][WARNING]: Unhandled notification { "params": { "id": "5" }, "method": "$/cancelRequest", "jsonrpc": "2.0" }
2024-04-24 07:33:37,241 [  18681]   INFO - #c.i.p.l.i.LspServerImpl - SemgrepLspServerDescriptor@sammy(Running;2): STDERR: [0m
2024-04-24 07:33:37,241 [  18681]   INFO - #c.i.p.l.i.LspServerImpl - SemgrepLspServerDescriptor@sammy(Running;2): STDERR: 
2024-04-24 07:33:37,241 [  18681]   INFO - #c.i.p.l.i.LspServerImpl - SemgrepLspServerDescriptor@sammy(Running;2): STDERR: ┌─────────────┐
2024-04-24 07:33:37,241 [  18681]   INFO - #c.i.p.l.i.LspServerImpl - SemgrepLspServerDescriptor@sammy(Running;2): STDERR: │ Scan Status │
2024-04-24 07:33:37,241 [  18681]   INFO - #c.i.p.l.i.LspServerImpl - SemgrepLspServerDescriptor@sammy(Running;2): STDERR: └─────────────┘
2024-04-24 07:33:37,241 [  18681]   INFO - #c.i.p.l.i.LspServerImpl - SemgrepLspServerDescriptor@sammy(Running;2): STDERR:   Scanning 2 files tracked by git with 1779 Code rules:
2024-04-24 07:33:37,241 [  18681]   INFO - #c.i.p.l.i.LspServerImpl - SemgrepLspServerDescriptor@sammy(Running;2): STDERR: 
2024-04-24 07:33:37,241 [  18681]   INFO - #c.i.p.l.i.LspServerImpl - SemgrepLspServerDescriptor@sammy(Running;2): STDERR:   Language      Rules   Files          Origin      Rules
2024-04-24 07:33:37,242 [  18682]   INFO - #c.i.p.l.i.LspServerImpl - SemgrepLspServerDescriptor@sammy(Running;2): STDERR:  ─────────────────────────────        ───────────────────
2024-04-24 07:33:37,242 [  18682]   INFO - #c.i.p.l.i.LspServerImpl - SemgrepLspServerDescriptor@sammy(Running;2): STDERR:   <multilang>      93       2          Community     126
2024-04-24 07:33:37,242 [  18682]   INFO - #c.i.p.l.i.LspServerImpl - SemgrepLspServerDescriptor@sammy(Running;2): STDERR:   php              65       2          Custom          1
2024-04-24 07:33:37,242 [  18682]   INFO - #c.i.p.l.i.LspServerImpl - SemgrepLspServerDescriptor@sammy(Running;2): STDERR:                                        Pro_rules      31
2024-04-24 07:33:37,242 [  18682]   INFO - #c.i.p.l.i.LspServerImpl - SemgrepLspServerDescriptor@sammy(Running;2): STDERR: 
2024-04-24 07:33:37,242 [  18682]   INFO - #c.i.p.l.i.LspServerImpl - SemgrepLspServerDescriptor@sammy(Running;2): STDERR: [15.22][WARNING]: Unhandled message
2024-04-24 07:33:37,928 [  19368]   INFO - #c.i.p.l.i.LspServerImpl - SemgrepLspServerDescriptor@sammy(Running;2): STDERR: [0m[15.91][ERROR]: exn (Parsing_error.Syntax_error (/Users/aram/Documents/workspace/sammy/src/Entity/AssessmentAnswer.php:38:5 "\\")) with Pfff parser
2024-04-24 07:33:37,961 [  19401]   INFO - #c.i.p.l.i.LspServerImpl - SemgrepLspServerDescriptor@sammy(Running;2): STDERR: [0m[15.94][ERROR]: exn (Parsing_error.Syntax_error (/Users/aram/Documents/workspace/sammy/src/Entity/Remark.php:38:5 "\\")) with Pfff parser```

Thanks for the help.

**Comment by ajbt200128** [comment]
those errors are pretty standard. By default the extension only scans lines in files that have been changed since the last commit (similar to pre-commit), so if there are no changes then there won't be anything showing up. If you want the extension to scan everything no matter what, you can try turning off "Only Git Dirty" in settings. You can also click the semgrep icon in the status bar and hit "scan all files in workspace" to see if that produces findings you want, this command is similar to disabling only git dirty, but is only temporary

**Comment by aramhovsepyan** [comment]
Hi Austin,
I have the "only git dirty" false. Semgrep does find issues when I run it manually from the command line. 
However that was the problem yesterday. Meanwhile the plugin stopped working both on PHPStorm and PyCharm.
The only semgrep log in the idea.log is this one.
`2024-04-25 06:35:26,699 [    165]   INFO - #c.i.i.p.PluginManager - Loaded custom plugins: Stylus (241.14494.140), Ideolog (222.3.2.0), String Manipulation (9.12.0), .env files support (2024.1), PHP Toolbox (6.2.0), PHP Annotations (10.0.0), Symfony Support (2023.1.270), Semgrep (0.2.4)`

I did notice that yesterday I had the language server running, now it doesn't. PHPStorm is version 2024.1, PyCharm is 2024.1.RC.
Thanks a lot for the help so far.

**Comment by ajbt200128** [comment]
>  However sometimes the LSP crashes and shows an error warning.
What is the error warning? If it's login related, try upgrading to semgrep 1.70.0, which fixes this (1.70.0 was released yesterday)
>Also is there a way to get an overview of all findings? 
No there's not a way to do so currently, due to a limitation of IntelliJ itself. We'll be keeping track to improvements of the SDK they provide (for LSP support), and if they add support for this, we'll definitely get it working, but for now there's no way for us to do this easily, and in a way that would pass IntelliJ's review process
